global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ipgeolocalizer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['https://ipgeolocalizer-production.up.railway.app']

